INSERT INTO SPORT (Label) VALUES ('CYCLISME'),('FOOTBALL'),('COURSE'), ('ATHLETISME'), ('BOXE'), ('HANDBALL'), ('VOLLEY'), ('RUGBY'),
 ('KAYAK'), ('GOLF'), 
('PING-PONG'), 
('ESCRIME'), ('BADMINTON'),
 ('ESCALADE') , 
('JUDO'), ('SKI'), ('SNOWBOARD'), ('SKATE'), ('BMX'), ('NATATION'), ('MOTO'), ('MUSCULATION'), ('CRICKET') ,('ACCROBRANCHE');
